package it.topnetwork.smartdpi.utility.constants;

public interface ErrorCode {

	int AUTH_TOKEN = 403;
	int GENERIC_ERROR  = 460;
	int GENERIC_DB_ERROR = 461;
	int FIND_RESULT = 462;
	int WRONG_CREDENTIAL = 463;
	int FIND_EMAIL_ADDRESS = 464;
	int SAME_PASSWORD = 465;
	int MISSING_FIELDS = 466;
	int ALREADY_ESISTS = 467;
	int SETTORE_COMMESSA_ASSOCIATED = 468;
	int SETTORE_KIT_ASSOCIATED = 469;
	int DPI_KIT_ASSOCIATED = 470;
	int COMMESSA_SEDI_ASSOCIATED = 471;
	int INTERVENTI_SEDE_COMMESSA_ASSOCIATED = 472;
	int DPI_KIT_ASSOCIATED_OTHER = 473;
	int DATE_PERIOD_INVALID = 474;
	int KIT_OPERATORE_MISMATCH = 475;
	int OPERATORE_CRM = 476;
	int ALLARME_OPERATORE = 477;
	int ALLARME_LAVORATO = 478;
	int ALLARME_DA_LAVORARE = 479;
	int ALLARME_CHIUSO = 480;
	int ALLARME_DPI = 481;
	int OPERATORE_COMMESSA_ASSOCIATED = 482;	
	
}